name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # -----------------
  # 1. CI: Run tests
  # -----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

  # -----------------
  # 2. CD: Deploy to GCP VM
  # -----------------
  deploy:
    runs-on: ubuntu-latest
    needs: build   # 🚀 Only runs if CI passes

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /home/ubuntu/app || https://github.com/JagritDua/Basic-Project.git /home/ubuntu/app
            cd /home/ubuntu/app
            git pull origin main
            pip3 install -r requirements.txt
            pkill -f "python3 app.py" || true
            nohup python3 app.py > app.log 2>&1 &
